# Generated by Django 3.1.5 on 2021-01-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('stars', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='price_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_of_start', models.CharField(max_length=45)),
                ('cost', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='transport_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=45)),
                ('number_of_places', models.CharField(max_length=45)),
                ('id_price_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.price_list')),
            ],
        ),
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
                ('duration', models.CharField(max_length=45)),
                ('id_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='punkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_punkt', models.CharField(max_length=45)),
                ('id_price_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.price_list')),
                ('id_tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.tour')),
            ],
        ),
        migrations.AddField(
            model_name='price_list',
            name='id_punkt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.punkt'),
        ),
        migrations.AddField(
            model_name='price_list',
            name='id_tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.tour'),
        ),
        migrations.AddField(
            model_name='price_list',
            name='id_transport_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.transport_type'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='id_punkt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.punkt'),
        ),
    ]
